name: bukalemun
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider:
  flare_flutter: ^1.5.5
  camera: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/assets/bukalemunlogo.png
    - assets/assets/conference.png
    - assets/assets/conference03.png
    - assets/assets/conferenceHighlighted.png
    - assets/assets/forum.png
    - assets/assets/forumHighlighted.png
    - assets/assets/profile.png
    - assets/assets/profileHighlighted.png
    - assets/assets/safari.png
    - assets/assets/safariHighlighted.png
    - assets/assets/addStory.png
    - assets/assets/iceBreakersBtn.png
    - assets/assets/conferenceMapBtn.png
    - assets/assets/addFriendBtn.png
    - assets/assets/addStory.png
    - assets/assets/Asset 6.png
    - assets/assets/bukalemunlogoLight.png
    - assets/assets/upBtn.png
    - assets/assets/downBtn.png
    - assets/assets/emptyChat.png
    - assets/assets/filledChat.png
    - assets/assets/shareBtn.png
    - assets/flare/splashAnimation.flr
    - assets/assets/hybridBackGround.png
    - assets/assets/hybridBrand.png
    - assets/assets/loginHeader.png
    - assets/assets/signUpFooter.png
    - assets/assets/insta.png
    - assets/assets/snap.png
    - assets/assets/school1.png
    - assets/assets/school2.png
    - assets/assets/school3.png
    - assets/assets/school4.png
    - assets/assets/school5.png
    - assets/assets/school6.png
    - assets/assets/school7.png
    - assets/assets/school8.png
    - assets/assets/school9.png
    - assets/assets/school10.png
    - assets/assets/school11.png
    - assets/assets/school12.png
    - assets/assets/school13.png
    - assets/assets/school14.png
    - assets/assets/school15.png
    - assets/assets/school16.png
    - assets/assets/school17.png
    - assets/assets/school18.png
    - assets/assets/school19.png
  fonts:
    - family: HelveticaNeuee
      fonts:
        - asset: assets/fonts/HelveticaNeue.otf
        - asset: assets/fonts/HelveticaNeue-thin.otf
          style: italic

